# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HXPhotoTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'HXPhotoPicker'
  # Pods for HXPhotoTest

  target 'HXPhotoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXPhotoTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
