# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TZPhotoTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'TZImagePickerController'
  # Pods for TZPhotoTest

  target 'TZPhotoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TZPhotoTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
