# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GXRACDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GXRACDemo
    pod 'ReactiveObjC', '~> 3.1.1'
end
